name: Update NSE Data

on:
  schedule:
    # Runs every 15 minutes, Mon-Fri, between 3:45 AM UTC and 10:00 AM UTC
    - cron: '*/15 4-10 * * 1-5'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install nsepython

      - name: Fetch NSE Data
        run: python fetch_data.py

      - name: Commit and Push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Action Bot"
          author_email: "actions@github.com"
          message: "Update real-time NSE data"
          add: "data.json"
